### PR TITLE
Fix some typo in chapter 1 & 2

### PR DESCRIPTION
**Pull request by guodhu**

### CODE REVIEW

**Comment by hefengxian** [comment]
First of all, thank you for your commits addressing those typo fixes. I have carefully reviewed your changes.

- The word `alga` is in singular form, but later, you submitted another commit to change it back.
- Submitting only the file `vocabulary.txt` is insufficient, as the actual working file on the page is `vocabulary.js`. The reason for using `vocabulary.txt` is for more convinent to input the words
- Therefore, the correct steps to fix typos are as follows:
    1. Amend the typos in `vocabulary.txt`.
    2. Use the terminal to navigate to the directory `src/pages/vocabulary/`
    3. Use Python to execute `python3 parser.py` to regenerate `vocabulary.js`
    4. Submit changes for both `vocabulary.js` and `vocabulary.txt`

Please follow the steps mentioned above and resubmit your changes. Additionally, I'm considering adding these instructions to the `README.md`

**Comment by guodhu** [comment]
Maybe you should consider remove the `vocabulary.js` from project. It's just intermediate product of the deploy and makes no sense to version control it, and obviously causes confusion.

**Comment by guodhu** [comment]
Anyway, I will create an issue and leave the typo to you.

**Comment by hefengxian** [comment]
> Anyway, I will create an issue and leave the typo to you.

I suppose this way is more better

**Pull request closed without merging**
